name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            binary_name: btc-brute-force-v${{ github.ref_name }}-linux-amd64
          - goos: linux
            goarch: arm64
            binary_name: btc-brute-force-v${{ github.ref_name }}-linux-arm64
          - goos: windows
            goarch: amd64
            binary_name: btc-brute-force-v${{ github.ref_name }}-windows-amd64.exe
          - goos: darwin
            goarch: amd64
            binary_name: btc-brute-force-v${{ github.ref_name }}-macos-amd64
          - goos: darwin
            goarch: arm64
            binary_name: btc-brute-force-v${{ github.ref_name }}-macos-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o ${{ matrix.binary_name }} ./cmd/btc-brute-force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: ${{ matrix.binary_name }}
          retention-days: 30

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/btc-brute-force-v*-linux-amd64
            **/btc-brute-force-v*-linux-arm64
            **/btc-brute-force-v*-windows-amd64.exe
            **/btc-brute-force-v*-macos-amd64
            **/btc-brute-force-v*-macos-arm64
          generate_release_notes: true
          draft: false
          prerelease: false
