name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22", "1.23"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify dependencies
        run: go mod verify

      - name: Download dependencies
        run: go mod download

      - name: Run go vet
        run: go vet ./cmd/btc-brute-force ./bench

      - name: Run unit tests
        run: go test -v ./...
        continue-on-error: false

      - name: Run benchmarks (quick)
        run: go test -bench=. -benchmem -benchtime=1s ./bench
        continue-on-error: true

      - name: Build binary
        run: make build

      - name: Test binary exists
        run: |
          if [ ! -f bin/btc-brute-force ]; then
            echo "Binary not found!"
            exit 1
          fi
          echo "✓ Binary built successfully"

      - name: Test binary help
        run: |
          ./bin/btc-brute-force 2>&1 | grep -q "Usage" || exit 1
          echo "✓ Binary executes correctly"
